# Chapter 1. Linear Algebra - Review

Here, we provide some examples of linear algebra and the usage of Numpy Arrays.

Copyright:



## 1.2 Numpy Array

The given array below is set to print out 3 rows and 5 columns as we can see all printed in zeros which we got when using .zeros(( , )) 

In [ ]:
import numpy as np
a = np.zeros((3, 5))
# note the extra bracket you need for calling np.zeros
print(a, '\n')

# shape of the array
print('len =',len(a))
print('shape =',a.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

len = 3
shape = (3, 5)


In this particular python code below we are given the parameters (3,5) which then are used to indicate the number of dimensions in the array which is shown by ".shape" the x-axis being 3 and the y-axis being 5.

In [ ]:
# pick two output valuables from a method
a = np.zeros((3,5))
nx,ny = a.shape
print('nx =', nx)
print('ny =', ny)

nx = 3
ny = 5


Each array below A,B, and C each contain 3 rows and 5 columns which we get due to the parameters given each one being printed with 7's

In [ ]:
# ways to generate a constant array

a = np.zeros((3,5)) + 7
print(a, '\n')

b = np.ones((3,5)) * 7
print(b, '\n')

c = np.full((3,5), 7)
print(c)

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]] 

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]] 

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


The given array below contains 5 rows and 5 columns; the array being 2-d with 1's and 0's due to the .eye function.

In [ ]:
# identity matrix function eye()
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


in the given array below we have 3 set of numbers which each set of numbers within the brackets represents an index.

In [ ]:
# index
a = np.array(([1,2], [3,4], [5,6]))
print(a)

[[1 2]
 [3 4]
 [5 6]]


The Two arrays below are given are fixed arrays that we have based on the parameters we plugged in, the second print out of b = a[:2, 1:3] indicates the indexes of the initial array giving us [2 3] [6 7]

In [ ]:
# slice index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b = a[:2, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In this array below we are given three sets of numbers which all together have their own index. In the second print out of b = a[1, :]
print(b) we are given to print out index 1 which in this case is [5,6,7,8].

In [10]:
# mix integer and slice index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) 
print(a)
b = a[1, :]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]


In [ ]:
# use two list as index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, '\n')
print(a[[0,1,2],[2,1,2]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[ 3  6 11]


The array given below as we can see is derived of 3 rows as well as 3 columns, all printed within range of indexes 0-2 we can see this happening on "for i in range(3):" In the second print out of the code we see in the second set of number everything increasing by 10, this is due to "a[1,:] += 10" which is indicating for everything in index "1" to be increased by 10.

In [11]:
# update values
a = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
print('before\n',a)

a[1,:] += 10
print('after\n',a)

before
 [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
after
 [[ 0.  1.  2.]
 [10. 11. 12.]
 [ 0.  1.  2.]]


The array given below as we can see is derived of 3 rows as well as 3 columns, all printed within range of indexes 0-2 we can see this happening on "for i in range(3):" The second print out of the code as we can see is derived of the same 3 rows and columns however index(2) in this case where the number 5's were printed was due to as we can see "a[:,2] = 5"

In [ ]:
a = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
print('before\n',a)

a[:,2] = 5.
print('after\n',a)

before
 [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
after
 [[0. 1. 5.]
 [0. 1. 5.]
 [0. 1. 5.]]


In the given array below we see that based on the parameters implemented we have an array with int 1. The second print out which was "int64" was a product that we got by ".dtype" which indicates how the bytes corresponds to the array which in this case is type "int"

In [12]:
a=np.array(([1,1],[1,1]))
print(a)
print(a.dtype)

[[1 1]
 [1 1]]
int64


In the given array below we see that based on the parameters implemented we have an array with "1." The second print out which was "float64" was a product that we got by ".dtype" which indicates how the bytes corresponds to the array in this case being type "float"

In [ ]:
a=np.array(([1.,1],[1,1])) 
print(a)
print(a.dtype)

[[1. 1.]
 [1. 1.]]
float64


In the given array below we see that based on the parameters implemented we have an array with "1" type "int" which we compare if every int is >2 being that none are which is why we see the all print out as "false" the second print out which was "bool" was printed due to the ".dtype" which indicates how the bytes corresponds to the array in this case being type "bool"

In [ ]:
a=np.array(([1.,1],[1,1]))>2  
print(a)
print(a.dtype)

[[False False]
 [False False]]
bool


The given code  below represents an array thats' data type is being defined in this case shown by "print(a.dtype)" because of this we get "<U1" which signifies the bit length of the given elements in this case '1', along with this we also get the byte order

In [ ]:
a=np.array((['1','1'],['1','1']))
print(a)
print(a.dtype)

[['1' '1']
 ['1' '1']]
<U1


This final array below is being represented as a float due to the "dtype=float" that is being implemented after the array. Because of this we get the data type once the code has been ran as a "float64"

In [ ]:
a=np.array((['1','1'],['1','1']),dtype=float) 
print(a)
print(a.dtype)

[[1. 1.]
 [1. 1.]]
float64
