# 3.4 Logistic Regression

Here we provide some examples of logistic regression using sklearn: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

Copyright:

## 1. Breast cancer dataset 

Given the python cell below as we can see by the output we are working with the two given points that are shown below on the output of the cell. One point being the x-axis in which looks to be a simple data point from the given set as well as the y-axis which is labeled as the target point from the same set of data.

In [ ]:
from sklearn.linear_model import LogisticRegression as LR
from sklearn.datasets import load_breast_cancer
from sklearn.datasets import load_iris
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
 
# breast cancer dataset    
data = load_breast_cancer()
X = data.data
y = data.target
X.data.shape

(569, 30)

In [ ]:
lrl1 = LR(penalty="l1",solver="liblinear",C=0.5,max_iter=1000)
lrl1 = lrl1.fit(X,y)
lrl1.coef_

(lrl1.coef_ != 0).sum(axis=1)#array([10])  

lrl2 = LR(penalty="l2",solver="liblinear",C=0.5,max_iter=1000)
lrl2 = lrl2.fit(X,y)
lrl2.coef_

array([[ 1.61331113e+00,  1.00124605e-01,  4.60084834e-02,
        -4.19839432e-03, -9.26228937e-02, -3.00484301e-01,
        -4.53250190e-01, -2.19778015e-01, -1.33074668e-01,
        -1.92576286e-02,  1.89635811e-02,  8.74998561e-01,
         1.32421950e-01, -9.53784314e-02, -9.62972408e-03,
        -2.53596204e-02, -5.83890299e-02, -2.67755115e-02,
        -2.73846616e-02, -8.05302929e-05,  1.28529688e+00,
        -3.00088054e-01, -1.74310770e-01, -2.23545072e-02,
        -1.70267493e-01, -8.77272211e-01, -1.15830085e+00,
        -4.22526360e-01, -4.12406225e-01, -8.66393364e-02]])

## 2. Iris dataset

The cell below as we can see uses the dataset from the imported "iris" data that was initialized above. From that we can gather from all the cells below the same "iris" data is being utilized to predict certain porbabilities as we can see by the array below. Furthermore utilizing the same dataset we can see the computation of a point in the output of the last cell as the "score".

In [ ]:
# load the data
X, y = load_iris(return_X_y=True)

# fit the data to the LR model
clf = LR(random_state=0).fit(X, y)

# give predictions
clf.predict(X[:2,:])

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([0, 0])

In [ ]:
clf.predict_proba(X[:2, :])

array([[9.81801790e-01, 1.81981959e-02, 1.43556907e-08],
       [9.71727348e-01, 2.82726221e-02, 3.00307256e-08]])

In [ ]:
clf.score(X, y)

0.9733333333333334